spring:
  application:
    name: twitch-chat-hit-counter-course
  output:
    ansi:
      enabled: ALWAYS


---
## Local dev configs
spring:
  config:
    activate:
      on-profile: default
  # Kafka Configs
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: test-group-id-20
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      # used to batch poll kafka messages
      max-poll-records: 500
      group-id-batch: test-group-id-batch-2
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  # MySql Configs
  datasource:
    url:
      jdbc:mysql://localhost:3306/dev_db
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Redis Configs
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: localhost
    port: 6379
    event-dedupe-database: 0
    greeting-feed-database: 1
    twitch-chat-event-dedupe-database: 2
    twitch-chat-hit-counter-database: 3

twitch-chat-hit-counter:
  kafka:
    producer:
      greeting-topic:
        greeting_events
      twitch-chat-topic:
        twitch_chat_events
    consumer:
      greeting-topic:
        greeting_events
      twitch-chat-topic:
        twitch_chat_events
  sql:
    greeting-table: greeting_events
    greeting-batch-table: greeting_batch_events
    twitch-chat-event-table: twitch_chat_events

