spring:
  application:
    name: twitch-chat-hit-counter-course
  output:
    ansi:
      enabled: ALWAYS


---
## Local dev configs
spring:
  config:
    activate:
      on-profile: default
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: test-group-id-15
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      # used to batch poll kafka messages
      max-poll-records: 500
      group-id-batch: test-group-id-batch-2
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  # MySql
  datasource:
    url:
      jdbc:mysql://localhost:3306/dev_db
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

twitch-chat-hit-counter:
  kafka:
    producer:
      greeting-topic:
        greeting_events
    consumer:
      greeting-topic:
        greeting_events
  sql:
    greeting-table: greeting_events
    greeting-batch-table: greeting_batch_events

